### ISSUE TITLE
Inventory results into segmentation fault

### ISSUE THREAD

**Issue by villinte** [luvbum/rop#2]
Opening up inventory randomly results into segmentation faults.

**Comment by martin-tornqvist** [comment]
Cannot recreate this.

It happens even with the starting inventory?

Try rebuilding from scratch?:

`$ make obj-clean`

**EDIT:** Hahaha, nevermind - I just clicked on the email notification and thought this was for IA ;-)

**Comment by villinte** [comment]
lol

**Comment by martin-tornqvist** [comment]
The way items are moved between different (C++) containers seems problematic.

In game.cpp, pickupItem is called with a reference to an item pointed to by the the global actors u-pointer vector. The ref is then passed to addItem, which pushes the address of this ref to a vector of raw pointers.

So - the "actors" vector is still the owner of this memory. Ownership has not been transfered, you have only created a "view" of the object (raw pointer). Aaaand it's gone.

In pickupItem, after calling addItem, you erase it from the actors vector - killing the sole owner of this memory - and thus destroying the object.

I would recommend implementing the container "inv" field as a vector of u-pointers instead, and actually **move** the entities there to transfer ownership.
